-- Add new columns to support SCN codes and document URLs
ALTER TABLE public.scm_knowledge 
ADD COLUMN IF NOT EXISTS scn_code text,
ADD COLUMN IF NOT EXISTS document_url text;

-- Create index on scn_code for faster lookups
CREATE INDEX IF NOT EXISTS idx_scm_knowledge_scn_code ON public.scm_knowledge(scn_code);

-- Update existing data and insert new data from SCM-2-2.xlsx
-- Clear existing data
TRUNCATE TABLE public.scm_knowledge;

-- Insert all data with SCN codes and document links
INSERT INTO public.scm_knowledge (question, answer, keywords, link, scn_code, document_url) VALUES
('What is a Purchase Order?', 'A Purchase Order (PO) is a commercial document and first official offer issued by a buyer to a seller indicating types, quantities, and agreed prices for products or services.', ARRAY['PO', 'definition', 'procurement'], NULL, NULL, NULL),
('How do I create a new vendor in SAP?', 'To create a new vendor, navigate to transaction FK01 in SAP, then fill in the required fields including vendor name, address, payment terms, and banking information.', ARRAY['vendor', 'SAP', 'create', 'FK01'], NULL, NULL, NULL),
('What are the steps for inventory reconciliation?', '1. Compare physical count to system records. 2. Investigate discrepancies. 3. Document findings. 4. Make necessary adjustments in the system.', ARRAY['inventory', 'reconciliation'], NULL, NULL, NULL),
('Who is the contact for logistics issues?', 'Please contact the logistics team at logistics@loblaw.ca for any logistics-related issues.', ARRAY['logistics', 'contact', 'issues'], 'mailto:logistics@loblaw.ca', NULL, NULL),
('How to create purchase orders', 'To create a purchase order login to SAP, navigate to ME21N, give the vendor details, item details, qty and DC and click on save.', ARRAY['PO', 'Create PO'], NULL, NULL, NULL),
('Login to MAWM', 'Open the URL: https://lobls2-auth.sce.manh.com/discover_user', ARRAY['MAWM', 'Login'], 'https://lobls2-auth.sce.manh.com/discover_user', NULL, NULL),

-- IB scenarios with execution documents
('IB-01 - Happy Path - Receive PO in FULL via DC ASN/ Putaway to Active', '1. Item profiling set up --> Ti * Hi --> update values in the multiples of pack and subpack from SAP. 2. Appointments to be created in C3 as it is NA in Manhattan', ARRAY['Steps', 'IB', 'steps of Sceanrio'], NULL, 'IB-01', NULL),
('IB-02 - Happy Path - Receive PO in FULL via Vendor ASN / Putaway to Reserve', '1. Item profiling set up --> Ti * Hi --> update values in the multiples of pack and subpack from SAP. 2. Appointments to be created in C3 as it is NA in Manhattan', ARRAY['Steps', 'IB', 'steps of Sceanrio'], NULL, 'IB-02', NULL),
('IB-03 - Receive PO - Overage + shortage | Damaged overage iLPNs / Putaway to T-zone', '1. Item profiling set up --> Ti * Hi --> update values in the multiples of pack and subpack from SAP. 2. Appointments to be created in C3 as it is NA in Manhattan', ARRAY['Steps', 'IB', 'steps of Sceanrio'], NULL, 'IB-03', NULL),
('IB-06 - Receive PO in FULL via DC ASN / Item on Recall/ Putaway to Active & T-Zone', '1. Item profiling set up --> Ti * Hi --> update values in the multiples of pack and subpack from SAP. 2. Appointments to be created in C3 as it is NA in Manhattan', ARRAY['Steps', 'IB', 'steps of Scenario', 'IB06'], NULL, 'IB-06', '/documents/IB06.docx'),
('IB-07 - Receive PO via Vendor ASN with incorrect qty - Receiving Correction - Post verification - Split LPN', '1. Item profiling set up --> Ti * Hi --> update values in the multiples of pack and subpack from SAP. 2. Appointments to be created in C3 as it is NA in Manhattan', ARRAY['Steps', 'IB', 'steps of Sceanrio'], NULL, 'IB-07', NULL),
('IB-08 - Cancel DC ASN (ASN should be In-Transit Status)', '1. Item profiling set up --> Ti * Hi --> update values in the multiples of pack and subpack from SAP. 2. Appointments to be created in C3 as it is NA in Manhattan', ARRAY['Steps', 'IB', 'steps of Sceanrio'], NULL, 'IB-08', NULL),
('IB-09 - Cancel Purchase lines/ Cancel Purchase Order in SAP', '1. Item profiling set up --> Ti * Hi --> update values in the multiples of pack and subpack from SAP. 2. Appointments to be created in C3 as it is NA in Manhattan', ARRAY['Steps', 'IB', 'steps of Sceanrio'], NULL, 'IB-09', NULL),
('IB-10 - Receive PO via DC ASN / Vendor Performance/ Putaway', '1. Item profiling set up --> Ti * Hi --> update values in the multiples of pack and subpack from SAP. 2. Appointments to be created in C3 as it is NA in Manhattan', ARRAY['Steps', 'IB', 'steps of Sceanrio'], NULL, 'IB-10', NULL),
('IB-11 - Receive PO via DC ASN - Copy LPN/ Putaway', '1. Item profiling set up --> Ti * Hi --> update values in the multiples of pack and subpack from SAP. 2. Appointments to be created in C3 as it is NA in Manhattan. 3. Putaway to Reserve: a. Low reach equipments - Task grp b. High reach Task group [7 to 9 Levels]', ARRAY['Steps', 'IB', 'steps of Sceanrio'], NULL, 'IB-11', NULL),
('IB-12 - Receive PO Partial via DC ASN / Edit PO delivery date /Putaway', '1. Item profiling set up --> Ti * Hi --> update values in the multiples of pack and subpack from SAP. 2. Appointments to be created in C3 as it is NA in Manhattan', ARRAY['Steps', 'IB', 'steps of Sceanrio'], NULL, 'IB-12', NULL),
('IB-13 - Receive PO with HOLD via DC ASN/ Putaway', '1. Item profiling set up --> Ti * Hi --> update values in the multiples of pack and subpack from SAP. 2. Appointments to be created in C3 as it is NA in Manhattan', ARRAY['Steps', 'IB', 'steps of Sceanrio'], NULL, 'IB-13', NULL),
('IB-14 - Receive PO via DC ASN/ with Item having a Receiving Lock code/ Complete Putaway', '1. Item profiling set up --> Ti * Hi --> update values in the multiples of pack and subpack from SAP. 2. Appointments to be created in C3 as it is NA in Manhattan', ARRAY['Steps', 'IB', 'steps of Sceanrio'], NULL, 'IB-14', NULL),
('IB-15 - Receive PO - Stack Pallet - Validate LPN Size Type and Location Size Type during System directed putaway', '1. Item profiling set up --> Ti * Hi --> update values in the multiples of pack and subpack from SAP. 2. Appointments to be created in C3 as it is NA in Manhattan. 3. Putaway to Reserve: a. Low reach equipments - Task grp b. High reach Task group [7 to 9 Levels]', ARRAY['Steps', 'IB', 'steps of Sceanrio'], NULL, 'IB-15', NULL),
('IB-16 - Receive PO with Trusted Vendor via Vendor ASN (Green Lane)/ Putaway', '1. Item profiling set up --> Ti * Hi --> update values in the multiples of pack and subpack from SAP. 2. Appointments to be created in C3 as it is NA in Manhattan', ARRAY['Steps', 'IB', 'steps of Sceanrio'], NULL, 'IB-16', NULL),
('IB-17 - Receive Interbranch PO/ WM2008 to MAWM (Active)', '1. Item profiling set up --> Ti * Hi --> update values in the multiples of pack and subpack from SAP. 2. Appointments to be created in C3 as it is NA in Manhattan', ARRAY['Steps', 'IB', 'steps of Sceanrio'], NULL, 'IB-17', NULL),
('IB-17.1 - Receive Interbranch PO (MAWM DC to MAWM DC)', '1. Item profiling set up --> Ti * Hi --> update values in the multiples of pack and subpack from SAP. 2. Appointments to be created in C3 as it is NA in Manhattan', ARRAY['Steps', 'IB', 'steps of Sceanrio'], NULL, 'IB-17.1', NULL),
('IB-18 - Exception Handling: (LPN, Item, Pk Qty, Receiving & Code Date exceptions, un-assign ASN from Shipment, Un-Assign PO from ASN)', '1. Item profiling set up --> Ti * Hi --> update values in the multiples of pack and subpack from SAP. 2. Appointments to be created in C3 as it is NA in Manhattan', ARRAY['Steps', 'IB', 'steps of Sceanrio'], NULL, 'IB-18', NULL),
('IB-19 - Partial Replen Putaway to Active and Reserve / FIFO condition is met and Partial Replen Flag is Y', '1. Item profiling set up --> Ti * Hi --> update values in the multiples of pack and subpack from SAP. 2. Appointments to be created in C3 as it is NA in Manhattan', ARRAY['Steps', 'IB', 'steps of Sceanrio'], NULL, 'IB-19', NULL),
('IB-21 - Putaway to Reserve / FIFO condition is met and Partial Replen Flag is N', '1. Item profiling set up --> Ti * Hi --> update values in the multiples of pack and subpack from SAP. 2. Appointments to be created in C3 as it is NA in Manhattan', ARRAY['Steps', 'IB', 'steps of Sceanrio'], NULL, 'IB-21', NULL),
('IB-23 - Receiving Same Item on Multiple ASNs (Item Level/LPN level) and Single Inbound delivery/ Item on Recall / Putaway to T-zone', '1. Item profiling set up --> Ti * Hi --> update values in the multiples of pack and subpack from SAP. 2. Appointments to be created in C3 as it is NA in Manhattan', ARRAY['Steps', 'IB', 'steps of Sceanrio'], NULL, 'IB-23', NULL),
('IB-26 - Receive LPN Level ASN & PO/ Vendor Performance/ Putaway', '1. Item profiling set up --> Ti * Hi --> update values in the multiples of pack and subpack from SAP. 2. Appointments to be created in C3 as it is NA in Manhattan. 3. PO should be created with 5-6 items with 3*TiHi values and multiple ILPNS should be created to validating putaway login prefer zone as per the details mentioned in config guide. 4. Wac 17 - Putaway logic prefer zone from top to bottom', ARRAY['Steps', 'IB', 'steps of Sceanrio'], NULL, 'IB-26', NULL);